#!/usr/bin/env bash
# Copyright 2012 Jan Pokorny <xpokor04@stud.fit.vutbr.cz,
#                             pokorny_jan@seznam.cz>
#
# This file is part of clsp/predator.
#
# predator is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# predator is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with predator.  If not, see <http://www.gnu.org/licenses/>.

export LANG=C
set -eu
shopt -s extglob

HERE=$(dirname "${BASH_SOURCE[0]}")

: ${EXEC:="${HERE}/clsp"}
: ${PREDATOR_DIR:="${HERE}/dep-predator"}
# currently available: cl_smoke_test, fwnull, sl, fa or <empty>
: ${ANALYZER:=cl_smoke_test}

INT_ARGS=

# WRAPPER (e.g., "gdb -args")
# GCC_INCLUDES
# NOCOLOR

if echo ${ANALYZER} | grep -q "test"; then
    LIB="${PREDATOR_DIR}/${ANALYZER%_smoke_test}_build/tests/lib${ANALYZER}.so"
else
    LIB="${PREDATOR_DIR}/${ANALYZER}_build/lib${ANALYZER}.so"
fi

if [ ${GCC_INCLUDES:=0} -ne 0 ]; then
    INT_ARGS+=" -isystem $(echo|cpp -Wp,-v - 2>&1 >/dev/null|grep -E "^[ ]*/"|head -n1|sed 's/^ *//')"
fi

# gdb extensions (cgdb) seem not to like colors
if [[ "${WRAPPER:=}" = *[[:alpha:]]gdb* ]] && [ ${NOCOLOR:=1} -eq 1 ]; then
    NOCOLOR=1
fi

if [ ${NOCOLOR:=0} -ne 0 ]; then
    INT_ARGS+=" --clr-debug --clr-sp --clr-cl --clr-cl-debug --clr-warn"
fi

verbosely () {
    test ${VERBOSE:=0} -eq 0 || echo "${*}"
    exec -a "$0" ${@}
}

# or parse ${EXEC} --version
if LANG=C ldd ${EXEC} | grep -q "not found"; then
    verbosely "${WRAPPER}" env LD_PRELOAD="${LIB}" "${EXEC}" ${INT_ARGS} "${@}"
else
    verbosely "${WRAPPER}" "${EXEC}" -cl-plugin="${LIB}" ${INT_ARGS} "${@}"
fi
