#!/usr/bin/env python
# Copyright 2012 Jan Pokorny <xpokor04@stud.fit.vutbr.cz,
#                             pokorny_jan@seznam.cz>
#
# This file is part of clsp/predator.
#
# predator is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# predator is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with predator.  If not, see <http://www.gnu.org/licenses/>.

"""\
Purpose-specific front-end to difflib

Get the ratio of match between two text-based files and if it fits
in the limit, accept the match (exit code 0), otherwise reject it
(exit code 1).  Either way, print informative value of this ratio.
"""

__author__ = "Jan Pokorny <xpokor04@stud.fit.vutbr.cz,pokorny_jan@seznam.cz>"

from sys import argv, exit as sysexit #, stderr
from os.path import exists
from difflib import SequenceMatcher

DEFAULT_LIMIT = 0.9970  # accept only very little variance by default

def simdiff(file1, file2):
    m = SequenceMatcher(None, open(file1).read(), open(file2).read())
    return m.quick_ratio() # m.ratio()

if __name__ == "__main__":
    if 3 <= len(argv) <= 4:
        limit = (4 == len(argv)) and float(argv[3]) or DEFAULT_LIMIT
        #print >> stderr, limit
        if exists(argv[1]) and exists(argv[2]):
            ret = round(simdiff(argv[1], argv[2]), 4)
            #print >> stderr, ret
            if (limit >= ret):
                print (ret)
                sysexit(1)
            print ("~ 1.00")
            sysexit(0)
        else:
            sysexit(2)
    else:
        print ("Usage: %(script)s file1 file2" % {"script": argv[0]})
        sysexit(2)
