#!/usr/bin/env python

__author__ = "Jan Pokorny <xpokor04@stud.fit.vutbr.cz,pokorny_jan@seznam.cz>"

"""\
Purpose-specific front-end to difflib

Get the ratio of match between two text-based files and if it is in the limit,
accept the match (exit code 0) or reject it (exit code 1), printing
informative value of the match ratio.
"""

from sys import argv, stderr, exit as sysexit
from os.path import exists
from difflib import SequenceMatcher

DEFAULT_LIMIT = 0.9970  # accept only very little variance

def simdiff(file1, file2):
    m = SequenceMatcher(None, open(file1).read(), open(file2).read())
    return m.quick_ratio() # m.ratio()

if __name__ == "__main__":
    if 3 <= len(argv) <= 4:
        limit = (4 == len(argv)) and float(argv[3]) or DEFAULT_LIMIT
        #print >> stderr, limit
        if exists(argv[1]) and exists(argv[2]):
            ret = round(simdiff(argv[1], argv[2]), 4)
            #print >> stderr, ret
            if (limit >= ret):
                print (ret)
                sysexit(1)
            print ("~ 1.00")
            sysexit(0)
        else:
            sysexit(2)
    else:
        print ("Usage: %(script)s file1 file2" % {"script": argv[0]})
        sysexit(2)
