#!/usr/bin/env python

from sys import argv, exit
from os.path import exists
import networkx as nx

def is_isomorphic(file1, file2):
    dm = nx.DiGraphMatcher(nx.read_dot(file1), nx.read_dot(file2))
    return dm.is_isomorphic()

if __name__ == "__main__":
    if len(argv) == 3:
        if exists(argv[1]) and exists(argv[2]):
            ret = is_isomorphic(argv[1], argv[2])
            print (ret and "TRUE" or "FALSE")
            if ret:
                exit(0)
            else:
                exit(1)
        else:
            exit(2)
    else:
        print ("Usage: %(script)s file1 file2" % {"script": argv[0]})
        exit(2)
